version: "3.8"

services:
  db:
    image: postgres:15
#    environment:
#      - POSTGRES_DB=feature_detector_db
#      - POSTGRES_USER=user
#      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    build: .
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    depends_on:
      - db
    ports:
      - "8002:8002"
    volumes:
      - .:/usr/src/app

volumes:
  postgres_data: