version: "3.8"

services:
  db:
    image: postgres:15
    env_file: .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    build: .
    depends_on:
      - db
    ports:
      - "8002:8002"
    volumes:
      - .:/usr/src/app

volumes:
  postgres_data: